### ISSUE TITLE
Blank html files

### ISSUE THREAD

**Issue by BenjaminHoegh** [ireade/caniuse-embed-polymer#1]
The html files doesn't show anything when see it the browser

**Comment by ireade** [comment]
Hi @HawkonDK . Can you be more specific? What html files are you talking about? Have you followed the instructions on how to use the element?

**Comment by BenjaminHoegh** [comment]
I just open the examples to see if it works, they was all blank.  then I try to do it myself and it was still blank

**Comment by ireade** [comment]
Please follow [these instructions](https://github.com/ireade/caniuse-embed-polymer/blob/master/README.md) on how you use the element.
