### ISSUE TITLE
Missing http

### ISSUE THREAD

**Issue by BenjaminHoegh** [ireade/caniuse-embed-polymer#2]
`<iframe src="//caniuse.bitsofco.de/embed/index.html?feat=viewport-units&amp;periods=future_1,current,past_1,past_2" frameborder="0" width="100%" height="392px"></iframe>`

**But should be:**
`<iframe src="http://caniuse.bitsofco.de/embed/index.html?feat=viewport-units&amp;periods=future_1,current,past_1,past_2" frameborder="0" width="100%" height="392px"></iframe>`

Don't know where in the code this happened, but I found out it not generate the http / https

**Comment by ireade** [comment]
Hey @HawkonDK . It's not supposed to have the protocol written. When written that way, the correct protocol is chosen based on the protocol of the page loading it.
